---
title: "Brain blood correlation"
author: 
  - Wei Zhang^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = T)
dir.base <- "../.."
dir.results <- file.path(dir.base, "analysis_results")
dir.cpg.test <- file.path(dir.results, "cpg_test")
dir.meta <- file.path(dir.results, "meta_analysis")
dir.dmr <- file.path(dir.results, "DMR")
dir.results.compare <- file.path(dir.results, "compare_study")
dir.data.aux <- file.path(dir.base,"../DATASETS/Aux_Sync/") 
dir.data.corr <- file.path(dir.base, "datasets/brain_blood_corr/")
dir.results.corr <- file.path(dir.results, "brain_blood_corr")
dir.data <- file.path(dir.base,"../DATASETS/") 
dir.london <- file.path(dir.data, "LONDON/")
dir.london.data <- file.path(dir.london, "DNAm/pca_filtering")
dir.london.pheno <- file.path(dir.london, "Phenotype/processed")
dir.results.compare <- file.path(dir.results, "compare_study")
for(p in grep("dir",ls(),value = T)) dir.create(get(p),recursive = TRUE,showWarnings = FALSE)
```

```{r}
library(tidyverse)
```

```{r message = F, warning=F}
source("../utility/annotation_and_bacon.R")
source("../utility/cpg_test.R")
source("../utility/plot.R")
```

# Load data

## London

```{r}
brain_beta <- readRDS(
  file.path(dir.london.data, "BRAIN/London_PFC_QNBMIQ_PCfiltered_withStageExclude.RDS")
)
brain_pheno <- readRDS(
  file.path(dir.london.pheno, "pheno107_PFC_withNeuronProp_withStageExclude_df.RDS")
)
blood_beta <- readRDS(
  file.path(dir.london.data, "BLOOD/London_QNBMIQ_PCfiltered_withStatusExclude.RDS")
)
blood_pheno <- readRDS(
  file.path(dir.london.pheno, "pheno_BLOOD_withBloodProp_withStatusExclude_df.rds")
)
```

## Limit samples in both datasets

```{r}
### Renames variables
colnames(brain_pheno)[c(1, 3:ncol(brain_pheno))] <- paste0(
  "brain_", colnames(brain_pheno)[c(1, 3:ncol(brain_pheno))]
)
colnames(blood_pheno)[c(1, 3:ncol(blood_pheno))] <- paste0(
  "blood_", colnames(blood_pheno)[c(1, 3:ncol(blood_pheno))]
)

### Merge datasets
pheno_final <- merge(
  brain_pheno, blood_pheno,
  by = "subject.id"
) #dim: 69 23

### Limit beta matrices to samples in pheno_final
brain_beta_final <- brain_beta[, pheno_final$brain_sample]
blood_beta_final <- blood_beta[, pheno_final$blood_sample]
```

## Significant CpGs

```{r}
# Single CpGs
results <- read_csv(
   file.path(dir.meta,
            "meta_analysis_FHS9_ADNI_results.csv"),
   show_col_types = F
) %>% 
  dplyr::select(cpg, seqnames, start, GREAT_annotation, estimate, se, pVal.fixed, direction) %>% 
  dplyr::rename_with(~paste0("aging_assoc_", .x), !c(cpg, seqnames, start, GREAT_annotation)) 
results_sig <- results %>% 
  filter(aging_assoc_pVal.fixed < 1e-05, aging_assoc_direction %in% c("++", "--")) %>%
  mutate(aging_assoc_direction = ifelse(aging_assoc_direction == "--", "-", "+"))
# DMR
sig.dmr.df <- read_csv(
  file.path(dir.dmr, "coMeth_combp_overlap_dmr.csv")
) 
sig.dmr <- str_split(sig.dmr.df$cpgs_in_region, ",") %>% unlist() 
common_cpg <- intersect(sig.dmr, results_sig$cpg)
all_cpg <- union(sig.dmr, results_sig$cpg)

results_sig <- results %>% 
  filter(cpg %in% all_cpg) %>%
  mutate(Source = ifelse(cpg %in% common_cpg, "individual CpG + CpG in DMR",
                   ifelse(cpg %in%  sig.dmr[! sig.dmr %in% common_cpg], "CpG in DMR", "individual CpG")))
```

# Calculate correlation

```{r}
### Limit blood_beta and brain_beta to probes in main_cpgs
brain_beta_cpgs <- brain_beta_final[
  row.names(brain_beta_final) %in% unique(c(sig.dmr, all_cpg)),
  ]

blood_beta_cpgs <- blood_beta_final[
  row.names(blood_beta_final) %in% unique(c(sig.dmr, all_cpg)),
  ]

identical(dim(brain_beta_cpgs), dim(blood_beta_cpgs))
```

## Residual

```{r message = F}
pheno_final$brain_slide <- as.character(pheno_final$brain_slide)
# brain residuals
brain_resid <- methyl_adj(
  mat = brain_beta_cpgs,
  pheno = pheno_final,
  adjust_var = c("brain_age.brain", "brain_sex", "brain_prop.neuron", "brain_slide"),
  convert_to_M = T,
  return_to_beta = F
)
# blood residuals
pheno_final$blood_Gran <- pheno_final$blood_Eosino + pheno_final$blood_Neutro
blood_resid <- methyl_adj(
  mat = blood_beta_cpgs,
  pheno = pheno_final,
  adjust_var = c("blood_age.blood", "blood_sex", "blood_slide", 
                 "blood_B", "blood_CD4T", "blood_NK", "blood_Gran", "blood_Mono"),
  convert_to_M = T,
  return_to_beta = F
)
``` 

```{r eval = F}
save(
  brain_resid,
  blood_resid,
  file = file.path(dir.data.corr, "LONDON_blood_brain_QNBMIQ_PCfiltered_mvalResiduals.rda")
)
```

```{r}
blood_brain_cor <- lapply(seq_len(nrow(brain_resid)), function(row){
  spearman_cor <- cor.test(
    brain_resid[row,],
    blood_resid[row,],
    method = "spearman", 
    exact = F
  )
  
  data.frame(
    cpg = row.names(brain_resid)[row],
    spearman_cor = spearman_cor$estimate,
    pVal = spearman_cor$p.value,
    stringsAsFactors = FALSE
  )
})

blood_brain_cor <- do.call(rbind, blood_brain_cor)
blood_brain_cor$fdr <- p.adjust(blood_brain_cor$pVal, method = "fdr")
blood_brain_cor
```

```{r eval = F}
write.csv(
  blood_brain_cor,
  file.path(dir.data.corr, "London_blood_brain_residuals_correlation_cpgs.csv"),
  row.names = FALSE
)
```


## Beta

```{r}
blood_brain_cor <-  plyr::adply(seq_len(nrow(brain_beta_cpgs)),
                                .margins = 1,
                                .fun =  function(row){
                                  spearman_cor <- cor.test(
                                    brain_beta_cpgs[row,],
                                    blood_beta_cpgs[row,],
                                    method = "spearman",
                                    exact = F
                                  )
                                  
                                  data.frame(
                                    cpg = row.names(brain_beta_cpgs)[row],
                                    spearman_cor = spearman_cor$estimate,
                                    pVal = spearman_cor$p.value,
                                    stringsAsFactors = FALSE
                                  )
                                },.id = NULL)

blood_brain_cor$fdr <- p.adjust(blood_brain_cor$pVal, method = "fdr")
blood_brain_cor
```

```{r eval = F}
write.csv(
  blood_brain_cor,
  file.path(dir.data.corr, "London_blood_brain_beta_correlation_cpgs.csv"),
  row.names = FALSE
)
```

# Merge results

```{r message = F}
corr_beta <- read_csv(
  file.path(dir.data.corr, "London_blood_brain_beta_correlation_cpgs.csv")
) %>%
  rename_with(~paste0("beta_", .x), !"cpg")
corr_res <- read_csv(
  file.path(dir.data.corr, "London_blood_brain_residuals_correlation_cpgs.csv")
) %>%
  rename_with(~paste0("res_", .x), !"cpg")
```

## Merge correlation results

```{r message = F, warning=F}
final_results <- full_join(
    corr_beta, corr_res
  )

final_results <- unique(final_results)
```

## Add annotation

```{r message = F}
library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
# Add annotation
final_results_annotate <- annotate_results(
  final_results,
  dir.data.aux = dir.data.aux,
  save = F
)
final_results_annotate <- annotate_chmm(
  final_results_annotate,
  dir.data.aux = dir.data.aux
)
```

## Merge meta analysis results

```{r}
final_results_annotate_meta <- left_join(
  final_results_annotate,
  results_sig %>% dplyr::select(cpg, aging_assoc_estimate, aging_assoc_se, aging_assoc_pVal.fixed, aging_assoc_direction, Source)
)

final_results_annotate_meta$aging_assoc_direction <- ifelse(final_results_annotate_meta$aging_assoc_estimate < 0, "-", "+")
```

```{r eval = F}
write_csv(
  final_results_annotate_meta,
  file.path(dir.results.corr, 
            "Brain_blood_correlation_results.csv")
)
```

## Merge with CpGs in comparison

```{r}
df <- readxl::read_xlsx(
  file.path(dir.results.compare, "Compare_study_aging_and_miamiad.xlsx")
)

df$aging_assoc_direction <- ifelse(df$aging_assoc_estimate < 0, "-", "+")

df2 <- inner_join(final_results_annotate_meta, df[,c(1,10:21)])
```

```{r eval = F}
write_csv(
  df2,
  file.path(dir.results.corr, 
            "Brain_blood_correlation_results_merge_compare_study.csv")
)
```

# Session Information

<details>
  <summary>**Session Info**</summary>
```{r session}
sessionInfo()
```
</details>


